name: Bridgecrew
on:
  push:
    branches:
      - master
jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Run Bridgecrew 
      id: Bridgecrew
      uses: bridgecrew/bridgecrew:2.0.639
      with:
        api-key: ${{ secrets.BRIDGECREW_API_KEY }}